workflows:
  ios-project-debug:
    name: iOS debug

    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "GameApp.xcodeproj"
        XCODE_SCHEME: "GameApp"

    scripts:
      - name: Diagnose
        script: |
          xcodebuild -version
          xcrun simctl list devices available
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -showdestinations

      - name: Run tests
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -destination "platform=iOS Simulator,id=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder" \
            -skipPackagePluginValidation \
            test

      - name: Build debug app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -skipPackagePluginValidation \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      email:
        recipients:
          - jonrysimbolon19@gmail.com
