workflows:
  ios-project-debug:
    name: iOS debug

    environment:
      xcode: latest
      vars:
        XCODE_PROJECT: "GameApp.xcodeproj"
        XCODE_SCHEME: "GameApp"

    scripts:
      - name: Diagnose
        script: |
          xcodebuild -version

          echo "===== RUNTIMES ====="
          xcrun simctl list runtimes

          echo "===== DEVICES ====="
          xcrun simctl list devices available

          echo "===== DESTINATIONS ====="
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -showdestinations

          echo "===== TEST TARGET ====="
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            -showBuildSettings | grep TEST

      - name: Build debug app
        script: |
          xcodebuild \
            -project "$XCODE_PROJECT" \
            -scheme "$XCODE_SCHEME" \
            clean build \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app

    publishing:
      email:
        recipients:
          - jonrysimbolon19@gmail.com
